# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 - AArch64 support for User Mode Linux
#

obj-y = registers.o mcontext.o tls.o

USER_OBJS := $(obj-y)

include $(srctree)/arch/um/scripts/Makefile.rules
